# Generated by Django 4.1.1 on 2022-10-02 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=264)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('brand', models.CharField(max_length=264)),
                ('category', models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('TV', 'Television'), ('WM', 'WashingMachine')], max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Andaman& Nicobar Islands', 'Andaman& Nicobar Islands'), ('Goa', 'Goa'), ('Karela', 'Karela'), ('Chandigarh', 'Chandigarh'), ('Madhya Pradesh', 'Madhya Pradesh'), ('West Bengal', 'West Bengal'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Haryana', 'Haryana'), ('Punjab', 'Pujab'), ('Manipur', 'Manipur')], max_length=50),
        ),
    ]
